apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: todo-app
spec:
  type: NodePort        # ← change from ClusterIP to NodePort
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
