apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret-sync
  namespace: todo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: postgres-secret  # Matches your postgres deployment
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: db-secret
