apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: django-secret
  namespace: todo-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

